package com.example.astro

import com.example.data.model.FestivalData

object FestivalProvider {

    fun getFestivals(): List<FestivalData> {
        return listOf(
            FestivalData(
                id = "f1",
                nameEn = "Raksha Bandhan",
                nameHi = "रक्षाबंधन (Raksha Bandhan)",
                dateString = "28 अगस्त 2026",
                dateIso = "2026-08-28",
                dayNameHi = "शुक्रवार",
                monthNameHi = "श्रावण",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "पूर्णिमा",
                isMajor = true,
                regionFilter = "ALL",
                significanceEn = "Festival of sibling bond and protection.",
                significanceHi = "भाई-बहन के पवित्र प्रेम एवं रक्षा सूत्र बांधने का पावन पर्व।",
                pujaVidhiHi = "भद्रा रहित समय में बहनें अपने भाइयों को तिलक लगाकर दाहिनी कलाई पर राखी बांधें।"
            ),
            FestivalData(
                id = "f2",
                nameEn = "Krishna Janmashtami",
                nameHi = "श्री कृष्ण जन्माष्टमी",
                dateString = "04 सितम्बर 2026",
                dateIso = "2026-09-04",
                dayNameHi = "शुक्रवार",
                monthNameHi = "भाद्रपद",
                pakshaHi = "कृष्ण पक्ष",
                tithiHi = "अष्टमी",
                isMajor = true,
                regionFilter = "ALL",
                significanceEn = "Birth anniversary of Lord Krishna.",
                significanceHi = "भगवान श्री कृष्ण का रोहिणी नक्षत्र में पावन अवतरण दिवस।",
                pujaVidhiHi = "मध्यरात्रि 12:00 बजे बाल गोपाल का पञ्चामृत स्नान कराकर माखन-मिश्री भोग अर्पित करें।"
            ),
            FestivalData(
                id = "f3",
                nameEn = "Ganesh Chaturthi",
                nameHi = "गणेश चतुर्थी (Ganesh Utsav)",
                dateString = "14 सितम्बर 2026",
                dateIso = "2026-09-14",
                dayNameHi = "सोमवार",
                monthNameHi = "भाद्रपद",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "चतुर्थी",
                isMajor = true,
                regionFilter = "ALL",
                significanceEn = "Festival welcoming Lord Ganesha.",
                significanceHi = "विघ्नहर्ता भगवान श्री गणेश जी की स्थापना एवं 10 दिवसीय जन्मोत्सव।",
                pujaVidhiHi = "शुभ मुहूर्त में गणपति जी की मिट्टी की मूर्ति स्थापित कर दुर्वा व मोदक अर्पित करें।"
            ),
            FestivalData(
                id = "f4",
                nameEn = "Sharad Navratri Start",
                nameHi = "शारदीय नवरात्रि घटस्थापना",
                dateString = "11 अक्टूबर 2026",
                dateIso = "2026-10-11",
                dayNameHi = "रविवार",
                monthNameHi = "आश्विन",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "प्रतिपदा",
                isMajor = true,
                regionFilter = "ALL",
                significanceEn = "Beginning of 9 sacred night festival of Goddess Durga.",
                significanceHi = "मां आदिशक्ति जगदम्बा की आराधना एवं 9 स्वरूपों का महापर्व।",
                pujaVidhiHi = "शुभ मुहूर्त में कलश स्थापना, अखण्ड ज्योति प्रज्वलन एवं नवार्ण मन्त्र जप।"
            ),
            FestivalData(
                id = "f5",
                nameEn = "Dussehra / Vijayadashami",
                nameHi = "विजयादशमी / दशहरा",
                dateString = "20 अक्टूबर 2026",
                dateIso = "2026-10-20",
                dayNameHi = "मंगलवार",
                monthNameHi = "आश्विन",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "दशमी",
                isMajor = true,
                regionFilter = "ALL",
                significanceEn = "Victory of Good over Evil.",
                significanceHi = "अधर्म पर धर्म एवं असत्य पर सत्य की विजय का महान प्रतीक।",
                pujaVidhiHi = "शमी पूजन, अस्त्र-शस्त्र पूजन एवं रावण दहन के उपरांत अपराजिता देवी पूजन।"
            ),
            FestivalData(
                id = "f6",
                nameEn = "Karwa Chauth",
                nameHi = "करवा चौथ (Karwa Chauth)",
                dateString = "29 अक्टूबर 2026",
                dateIso = "2026-10-29",
                dayNameHi = "गुरुवार",
                monthNameHi = "कार्तिक",
                pakshaHi = "कृष्ण पक्ष",
                tithiHi = "चतुर्थी",
                isMajor = true,
                regionFilter = "NORTH",
                significanceEn = "Fasting for spouse's longevity.",
                significanceHi = "पति की दीर्घायु एवं अखण्ड सौभाग्य हेतु सुहागिनों का निर्जला व्रत।",
                pujaVidhiHi = "सायंकाल माता पार्वती व शिव परिवार का पूजन तथा चन्द्रोदय पर अर्घ्यदान।"
            ),
            FestivalData(
                id = "f7",
                nameEn = "Dhanteras",
                nameHi = "धनतेरस / धन्वन्तरि जयन्ती",
                dateString = "06 नवम्बर 2026",
                dateIso = "2026-11-06",
                dayNameHi = "शुक्रवार",
                monthNameHi = "कार्तिक",
                pakshaHi = "कृष्ण पक्ष",
                tithiHi = "त्रयोदशी",
                isMajor = true,
                regionFilter = "ALL",
                significanceEn = "Festival of prosperity and health god.",
                significanceHi = "आरोग्य के देवता भगवान धन्वन्तरि व कुबेर देव का प्रकटीकरण पर्व।",
                pujaVidhiHi = "नवीन आभूषण, बर्तन एवं झाड़ू क्रय मुहूर्त। प्रदोष काल में यम दीपदान।"
            ),
            FestivalData(
                id = "f8",
                nameEn = "Diwali / Deepawali",
                nameHi = "दीपावली (Maha Lakshmi Puja)",
                dateString = "08 नवम्बर 2026",
                dateIso = "2026-11-08",
                dayNameHi = "रविवार",
                monthNameHi = "कार्तिक",
                pakshaHi = "अमावस्या",
                tithiHi = "अमावस्या",
                isMajor = true,
                regionFilter = "ALL",
                significanceEn = "Festival of Lights and Wealth Goddess Lakshmi.",
                significanceHi = "प्रकाश का महापर्व, माता महालक्ष्मी एवं भगवान श्री गणेश की आराधना।",
                pujaVidhiHi = "प्रदोष काल एवं स्थिर वृषभ लग्न में महालक्ष्मी पूजन, बही-खाता पूजन व दीपमाला प्रज्वलन।"
            ),
            FestivalData(
                id = "f9",
                nameEn = "Govardhan Puja / Annakut",
                nameHi = "गोवर्धन पूजा / अन्नकूट",
                dateString = "09 नवम्बर 2026",
                dateIso = "2026-11-09",
                dayNameHi = "सोमवार",
                monthNameHi = "कार्तिक",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "प्रतिपदा",
                isMajor = true,
                regionFilter = "NORTH",
                significanceEn = "Worship of Govardhan hill and nature.",
                significanceHi = "भगवान श्री कृष्ण द्वारा गोवर्धन पर्वत धारण एवं प्रकृति संवर्धन उत्सव।",
                pujaVidhiHi = "गोबर से गोवर्धन पर्वत बनाकर पूजन, 56 भोग अथवा अन्नकूट अर्पित करें।"
            ),
            FestivalData(
                id = "f10",
                nameEn = "Chhath Puja",
                nameHi = "छठ पूजा (Surya Sasthi)",
                dateString = "14 नवम्बर 2026",
                dateIso = "2026-11-14",
                dayNameHi = "शनिवार",
                monthNameHi = "कार्तिक",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "षष्ठी",
                isMajor = true,
                regionFilter = "NORTH",
                significanceEn = "Sun worship festival.",
                significanceHi = "प्रत्यक्ष देवता भगवान सूर्य एवं छठी मइया का अति कठिन 36 घंटे का निर्जला महापर्व।",
                pujaVidhiHi = "नदी/तालाब तट पर अस्ताचलगामी एवं उदीयमान सूर्यदेव को अर्घ्यदान।"
            ),
            FestivalData(
                id = "f11",
                nameEn = "Gangaur Teej",
                nameHi = "गणगौर तीज (Rajasthan Special)",
                dateString = "20 मार्च 2026",
                dateIso = "2026-03-20",
                dayNameHi = "शुक्रवार",
                monthNameHi = "चैत्र",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "तृतीया",
                isMajor = true,
                regionFilter = "RAJASTHAN",
                significanceEn = "Rajasthan's signature Gauri-Isar festival.",
                significanceHi = "राजस्थान का अति प्रसिद्ध लोकपर्व - माता गवरजा (पार्वती) एवं इसर जी (शिव) की भक्ति।",
                pujaVidhiHi = "होलिका की राख से गणगौर बनाकर 16 दिन सुहाग गीत गाकर पूजन व विसर्जन।"
            ),
            FestivalData(
                id = "f12",
                nameEn = "Teej Utsav (Hariyali Teej)",
                nameHi = "हरियाली तीज / कजरी तीज (Rajasthan)",
                dateString = "15 अगस्त 2026",
                dateIso = "2026-08-15",
                dayNameHi = "शनिवार",
                monthNameHi = "श्रावण",
                pakshaHi = "शुक्ल पक्ष",
                tithiHi = "तृतीया",
                isMajor = true,
                regionFilter = "RAJASTHAN",
                significanceEn = "Monsoon swing festival of Rajasthan.",
                significanceHi = "राजस्थान एवं उत्तर भारत की महिलाओं का लहरिया, झूले एवं सुहाग पर्व।",
                pujaVidhiHi = "हरे वस्त्र-झूले धारण कर शिव-पार्वती पूजन एवं घेवर-फेणी मिष्ठान भोग।"
            )
        )
    }
}
